__author__ = 'Wojciech Urbański'

import devices
import matplotlib.pyplot as plt

print("Setting up the system...")
config = devices.SystemConfiguration(1, 100)
print("...done.")
print("Setting up InputBlock...")
input_block = devices.SineInputBlock(config, 10, 100)
print(input_block.name())
print("...done.")
print("Adding block to the system...")
config.add_block(input_block)
print("Setting up PhaseModulatorBlock")
pm_block = devices.PhaseModulatorBlock(config, 10, 1)
print(pm_block.name())
print("...done.")
print("Adding block to the system...")
config.add_block(pm_block)
print("Listing blocks...")
config.list_blocks()
print("Connecting PhaseModulator to InputBlock...")
# pm_block.input(input_block)
config.refresh_blocks()
print("...done.")

print("Plotting input...")
plt.plot(pm_block.signal_in.signal)
plt.show()
plt.close()
print("...done")
print("Plotting output...")
plt.plot(pm_block.output().signal)
plt.show()
plt.close()
print("...done")